os: osx
osx_image: xcode10.1
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=CDMarkdownKit.xcworkspace
  - IOS_FRAMEWORK_SCHEME="CDMarkdownKit iOS"
  - MACOS_FRAMEWORK_SCHEME="CDMarkdownKit macOS"
  - TVOS_FRAMEWORK_SCHEME="CDMarkdownKit tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="CDMarkdownKit watchOS"
  - EXAMPLE_SCHEME="iOS Example"
  matrix:
    - DESTINATION="OS=5.1,name=Apple Watch Series 4 - 44mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=4.0,name=Apple Watch Series 3 - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=3.2,name=Apple Watch Series 2 - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=2.0,name=Apple Watch - 42mm"          SCHEME="$WATCHOS_FRAMEWORK_SCHEME" BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"

    - DESTINATION="OS=12.1,name=iPhone XS"                  SCHEME="$IOS_FRAMEWORK_SCHEME"     BUILD_FRAMEWORK="NO"  BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=11.1,name=iPhone X"                   SCHEME="$IOS_FRAMEWORK_SCHEME"     BUILD_FRAMEWORK="NO"  BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=10.1,name=iPhone 7 Plus"              SCHEME="$IOS_FRAMEWORK_SCHEME"     BUILD_FRAMEWORK="NO"  BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6"                    SCHEME="$IOS_FRAMEWORK_SCHEME"     BUILD_FRAMEWORK="NO"  BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=8.1,name=iPhone 4s"                   SCHEME="$IOS_FRAMEWORK_SCHEME"     BUILD_FRAMEWORK="NO"  BUILD_EXAMPLE="YES" POD_LINT="NO"

    - DESTINATION="OS=12.1,name=Apple TV 4K (at 1080p)"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=11.0,name=Apple TV 4K (at 1080p)"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=10.0,name=Apple TV 1080p"             SCHEME="$TVOS_FRAMEWORK_SCHEME"    BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=9.0,name=Apple TV 1080p"              SCHEME="$TVOS_FRAMEWORK_SCHEME"    BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"

    - DESTINATION="arch=x86_64"                             SCHEME="$MACOS_FRAMEWORK_SCHEME"   BUILD_FRAMEWORK="YES" BUILD_EXAMPLE="NO"  POD_LINT="YES"
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug if specified
  - if [ $BUILD_FRAMEWORK == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Framework in Release if specified
  - if [ $BUILD_FRAMEWORK == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --allow-warnings --use-libraries;
    fi
  
